#!/usr/bin/env python3
"""Generate Dart / Swift / Kotlin shape tables from shapes.json (single source of truth)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = json.loads((ROOT / "shapes.json").read_text())


def dart_prim(p: dict) -> str:
    if p["kind"] == "ellipse":
        return f"Primitive.ellipse({p['cx']}, {p['cy']}, {p['rx']}, {p['ry']})"
    return f"Primitive.rr({p['x']}, {p['y']}, {p['w']}, {p['h']}, {p['r']})"


def swift_prim(p: dict) -> str:
    if p["kind"] == "ellipse":
        return f".ellipse(cx: {p['cx']}, cy: {p['cy']}, rx: {p['rx']}, ry: {p['ry']})"
    return f".roundedRect(x: {p['x']}, y: {p['y']}, w: {p['w']}, h: {p['h']}, r: {p['r']})"


def kotlin_prim(p: dict) -> str:
    if p["kind"] == "ellipse":
        return f"Primitive.Ellipse({p['cx']}.0, {p['cy']}.0, {p['rx']}.0, {p['ry']}.0)"
    return f"Primitive.RoundedRect({p['x']}.0, {p['y']}.0, {p['w']}.0, {p['h']}.0, {p['r']}.0)"


def dart() -> str:
    rows = []
    for s in DATA["shapes"]:
        rows.append(
            "  Shape("
            f"key: '{s['key']}', regionId: '{s['regionId']}', side: Side.{s['side']}, "
            f"view: BodyView.{s['view']}, label: '{s['label']}', primitive: {dart_prim(s['primitive'])})"
        )
    body = ",\n".join(rows)
    return f"""// Generated by packages/mobile/generate.py — do not edit.
part of 'geometry.dart';

const List<Shape> kAllShapes = [
{body},
];
"""


def swift() -> str:
    rows = []
    for s in DATA["shapes"]:
        rows.append(
            "    Shape(key: \"{key}\", regionId: \"{regionId}\", side: .{side}, view: .{view}, "
            "label: \"{label}\", primitive: {prim})".format(
                key=s["key"],
                regionId=s["regionId"],
                side=s["side"],
                view=s["view"],
                label=s["label"],
                prim=swift_prim(s["primitive"]),
            )
        )
    body = ",\n".join(rows)
    return f"""// Generated by packages/mobile/generate.py — do not edit.
extension Shape {{
    static let all: [Shape] = [
{body}
    ]
}}
"""


def kotlin() -> str:
    rows = []
    for s in DATA["shapes"]:
        rows.append(
            "    Shape(\"{key}\", \"{regionId}\", Side.{side}, BodyView.{view}, \"{label}\", {prim})".format(
                key=s["key"],
                regionId=s["regionId"],
                side=s["side"],
                view=s["view"],
                label=s["label"],
                prim=kotlin_prim(s["primitive"]),
            )
        )
    body = ",\n".join(rows)
    return f"""// Generated by packages/mobile/generate.py — do not edit.
package com.healthtwin

internal val ALL_SHAPES: List<Shape> = listOf(
{body}
)
"""


def main() -> None:
    dart_path = ROOT.parent / "flutter" / "lib" / "src" / "shapes.g.dart"
    swift_path = ROOT.parent / "swift" / "Sources" / "HealthTwinCore" / "Shapes.generated.swift"
    kotlin_path = ROOT.parent / "android" / "src" / "main" / "kotlin" / "com" / "healthtwin" / "Shapes.kt"
    dart_path.parent.mkdir(parents=True, exist_ok=True)
    swift_path.parent.mkdir(parents=True, exist_ok=True)
    kotlin_path.parent.mkdir(parents=True, exist_ok=True)
    dart_path.write_text(dart())
    swift_path.write_text(swift())
    kotlin_path.write_text(kotlin())
    print(f"wrote {dart_path}")
    print(f"wrote {swift_path}")
    print(f"wrote {kotlin_path}")


if __name__ == "__main__":
    main()
